name: Build Windows Target
on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        shell: cmd
        run: |
          haxelib setup C:/haxelib
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.2
          haxelib install flixel 5.5.0
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib install flixel-addons 3.2.1
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib install actuate
          haxelib git faxe https://github.com
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git linc_luajit https://github.com
          haxelib git hxvm-luajit https://github.com
          haxelib list

      - name: Configure Lime
        run: |
          haxelib run lime setup

      - name: Compile Game
        run: |
          haxelib run lime build windows -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VS-Psychic-Windows
          path: export/release/windows/bin/*
